title = "Es0terkitty"
description = "Until we turn to dust, (ﾐゝᆽ╹ﾐ)"
base_url = "https://es0terikitty.github.io"
default_language = "en"
build_search_index = false
generate_feeds = false
taxonomies = []
