title = "Es0terkitty"
description = "Mine is not despair, but anhedonic inertia, meow. =^.^="
base_url = "https://es0terikitty.github.io"
default_language = "en"
build_search_index = false
generate_feeds = false
taxonomies = []
