title = "Crime and Punishment"
description = "by Fyodor Dostoevsky"
base_url = "https://es0terikitty.github.io/crime-punishment"
default_language = "en"
build_search_index = false
generate_feeds = false
taxonomies = []
